### ISSUE TITLE
what if the time for a specific s is infinity?

### ISSUE THREAD

**Issue by DnnnW** [changliuliu/TemporalOptimization#1]
Hello！THX for your work. 
I have a question about the  mapping from the s axis to the T axis.
Since then, we may have some Ti is infinity for a specific Si, I want to know is it solvable for such case?
Or Can we determine the Smax by a higher Planner?
![Untitled Diagram](https://user-images.githubusercontent.com/9283417/54068440-c3880400-4287-11e9-9b55-addf28bf886e.png)
For example, the T2, T3 may be infinity in the fig above.

**Comment by changliuliu** [comment]
To encode a temporal constraint, you must have a finite lower bound. But you can have an infinite upper bound.

**Comment by DnnnW** [comment]
Got it. Thanks a lot!
