### ISSUE TITLE
Missing term on h representation?

### ISSUE THREAD

**Issue by HongyiSun** [changliuliu/TemporalOptimization#2]
Hello! Thank you for your work.

There seems to be a missing term of **(t(i-1)+t(i-2))** on h(3) and h(4) equation on your code and paper, which should be 
```
h(3) = t(i)*t(i-1)*t(i-2)*(t(i)+t(i-1))*(t(i-1)+t(i-2))*(t(i)+t(i-1)+t(i-2));
```
And there maybe some minor changes on the dh term accordingly.
Please correct me if I am wrong. Thanks a lot!

**Comment by changliuliu** [comment]
Yes... It seems we are missing this term. Would you mind submitting a pull request of the correct version? Thanks!
